spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sha199412
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

server:
  port: 9091

#打印sql
logging:
  level:
    com.E001 : debug

#mybatis配置

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.E001
